version: 2
jobs:
  validate-code-azure:
    docker:
      - image: hashicorp/terraform:0.11.14
    steps:
      - checkout
      - run:
          name: Validate Terraform
          command: terraform validate -check-variables=false ./azure/
  validate-code-aws:
    docker:
      - image: hashicorp/terraform:0.11.14
    steps:
      - checkout
      - run:
          name: Validate Terraform
          command: terraform validate -check-variables=false ./aws/
  run-os-tests-inspec-azure:
    docker:
      - image: scarolan/inspec:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Inspec Tests for OS settings
          no_output_timeout: 45m
          command: |
            # Run inspec tests on the remote workstation
            mkdir -p test_results/inspec
            inspec exec -b winrm --show-progress --host uat-tf-vault.centralus.cloudapp.azure.com --user hashicorp --password $WORKSTATION_PASSWORD --reporter cli junit:test_results/inspec/results.xml -- azure/test/inspec/os
      - store_test_results:
          path: test_results
  run-os-tests-inspec-aws:
    docker:
      - image: scarolan/inspec:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Inspec Tests for OS settings (AWS)
          no_output_timeout: 45m
          command: |
            # Run inspec tests on the remote workstation
            mkdir -p test_results/inspec
            inspec exec -b winrm --show-progress --host uat-tf-vault.centralus.cloudapp.azure.com --user hashicorp --password $WORKSTATION_PASSWORD --reporter cli junit:test_results/inspec/results.xml -- aws/test/inspec/os
  run-creds-tests-inspec-azure:
    docker:
      - image: scarolan/inspec:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Inspec Tests for Azure Credentials
          no_output_timeout: 45m
          command: |
            # Run inspec tests on the remote workstation
            mkdir -p test_results/inspec
            inspec exec -b winrm --show-progress --host uat-tf-vault.centralus.cloudapp.azure.com --user hashicorp --password $WORKSTATION_PASSWORD --reporter cli junit:test_results/inspec/results.xml -- azure/test/inspec/creds
      - store_test_results:
          path: test_results
  run-creds-tests-inspec-aws:
    docker:
      - image: scarolan/inspec:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Inspec Tests for AWS Credentials
          no_output_timeout: 45m
          command: |
            # Run inspec tests on the remote workstation
            mkdir -p test_results/inspec
            inspec exec -b winrm --show-progress --host uat-tf-vault.centralus.cloudapp.azure.com --user hashicorp --password $WORKSTATION_PASSWORD --reporter cli junit:test_results/inspec/results.xml -- aws/test/inspec/creds
      - store_test_results:
          path: test_results
  run-terraform-tests-inspec-azure:
    docker:
      - image: scarolan/inspec:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Inspec Tests for Terraform Labs
          no_output_timeout: 45m
          command: |
            # Run inspec tests on the remote workstation
            mkdir -p test_results/inspec
            inspec exec -b winrm --show-progress --host uat-tf-vault.centralus.cloudapp.azure.com --user hashicorp --password $WORKSTATION_PASSWORD --reporter cli junit:test_results/inspec/results.xml -- azure/test/inspec/terraform
      - store_test_results:
          path: test_results
  run-terraform-tests-inspec-aws:
    docker:
      - image: scarolan/inspec:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Inspec Tests for Terraform Labs
          no_output_timeout: 45m
          command: |
            # Run inspec tests on the remote workstation
            mkdir -p test_results/inspec
            inspec exec -b winrm --show-progress --host uat-tf-vault.centralus.cloudapp.azure.com --user hashicorp --password $WORKSTATION_PASSWORD --reporter cli junit:test_results/inspec/results.xml -- aws/test/inspec/terraform
      - store_test_results:
          path: test_results
  run-vault-api-tests-inspec-azure:
    docker:
      - image: scarolan/inspec:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Inspec API Tests for Vault labs
          no_output_timeout: 5m
          command: |
            # Run inspec tests on the remote workstation
            mkdir -p test_results/inspec
            inspec exec --show-progress --reporter cli junit:test_results/inspec/results.xml -- azure/test/inspec/vault_api
      - store_test_results:
          path: test_results
  run-vault-cli-tests-inspec-azure:
    docker:
      - image: scarolan/inspec:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Inspec CLI Tests for Vault Labs
          no_output_timeout: 20m
          command: |
            # Run inspec tests on the remote workstation
            mkdir -p test_results/inspec
            inspec exec -b winrm --show-progress --host uat-tf-vault.centralus.cloudapp.azure.com --user hashicorp --password $WORKSTATION_PASSWORD --reporter cli junit:test_results/inspec/results.xml -- azure/test/inspec/vault_cli
      - store_test_results:
          path: test_results
  run-vault-dbcreds-tests-inspec-azure:
    docker:
      - image: scarolan/inspec:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Run Inspec dbcreds Tests for Vault Labs
          no_output_timeout: 20m
          command: |
            # Run inspec tests on the remote workstation
            mkdir -p test_results/inspec
            inspec exec --show-progress --reporter cli junit:test_results/inspec/results.xml -- azure/test/inspec/vault_dbcreds
      - store_test_results:
          path: test_results
  clean-up-uat-azure:
    docker:
      - image: microsoft/azure-cli:latest
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Clean up UAT environment
          no_output_timeout: 45m
          command: |
            # Delete the UAT environment
            az login --service-principal -u 91299f64-f951-4462-8e97-9efb1d215501 -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID;
            az group delete -y --name uat-tf-vault-lab-workshop;
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate-code-aws
      - validate-code-azure
      - run-os-tests-inspec-aws:
          requires:
            - validate-code-aws
      - run-os-tests-inspec-azure:
          requires:
            - validate-code-azure
      - run-creds-tests-inspec-aws:
          requires:
            - run-os-tests-inspec-aws
      - run-creds-tests-inspec-azure:
          requires:
            - run-os-tests-inspec-azure
      - run-terraform-tests-inspec-aws:
          requires:
            - run-creds-tests-inspec-aws
      - run-terraform-tests-inspec-azure:
          requires:
            - run-creds-tests-inspec-azure
      - run-vault-api-tests-inspec-azure:
          requires:
            - run-terraform-tests-inspec-azure
      - run-vault-cli-tests-inspec-azure:
          requires:
            - run-vault-api-tests-inspec-azure
      - run-vault-dbcreds-tests-inspec-azure:
          requires:
            - run-vault-cli-tests-inspec-azure
      - clean-up-uat-azure:
          requires:
            - run-vault-dbcreds-tests-inspec-azure
  nightly-build:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - validate-code-aws
      - validate-code-azure
      - run-os-tests-inspec-aws:
          requires:
            - validate-code-aws
      - run-os-tests-inspec-azure:
          requires:
            - validate-code-azure
      - run-creds-tests-inspec-aws:
          requires:
            - run-os-tests-inspec-aws
      - run-creds-tests-inspec-azure:
          requires:
            - run-os-tests-inspec-azure
      - run-terraform-tests-inspec-aws:
          requires:
            - run-creds-tests-inspec-aws
      - run-terraform-tests-inspec-azure:
          requires:
            - run-creds-tests-inspec-azure
      - run-vault-api-tests-inspec-azure:
          requires:
            - run-terraform-tests-inspec-azure
      - run-vault-cli-tests-inspec-azure:
          requires:
            - run-vault-api-tests-inspec-azure
      - run-vault-dbcreds-tests-inspec-azure:
          requires:
            - run-vault-cli-tests-inspec-azure
      - clean-up-uat-azure:
          requires:
            - run-vault-dbcreds-tests-inspec-azure